

COLUMNS:
 NUMERICAL:
   -
     -
       -
         -

  CATEGORICAL:
    -
      -
        -
          -
            -

CLASSIFIERS:
  -RANDOMFORESTCLASSIFIER
  -GRADIENTBOOSTINGCLASSIFIER
  -RANDOMFORESTCLASSIFIER
  -DECISIONTREECLASSIFIER
  -EXTRATREECLASSIFIER
  -KNEIGHBORSCLASSIFIER
  -BERNOULLINB

BLENDING:
  FIRST_LEVEL: ["RANDOMFORESTCLASSIFIER", "GRADIENTBOOSTINGCLASSIFIER", "RANDOMFORESTCLASSIFIER"]
  SECOND_LEVEL: "LINEARREGRESSION"

VOTING_CLASSIFIERS: ["RANDOMFORESTCLASSIFIER", "GRADIENTBOOSTINGCLASSIFIER", "RANDOMFORESTCLASSIFIER"]

